source 'https://rubygems.org'

gem 'rails', '3.2.19'
gem 'sqlite3'
gem 'locomotive_cms', '~> 2.5.6', :require => 'locomotive/engine'

group :assets do
  gem 'compass',        '~> 0.12.7'
  gem 'compass-rails',  '~> 2.0.0'
  gem 'sass-rails',     '~> 3.2.6'
  gem 'coffee-rails',   '~> 3.2.2'
  gem 'uglifier',       '~> 2.5.1'
  gem 'therubyracer', :platforms => :ruby
end

gem 'unicorn'
